


//#############  Using only the new system where idle load is constant to represent on load #####
#define POWERNODECONSTS_PROTOLATHE_CONSTANT_LOAD 300

#define POWERNODECONSTS_IGNITER_CONSTANT_LOAD 30

#define POWERNODECONSTS_METER_CONSTANT_LOAD 5


#define POWERNODECONSTS_LIGHTING_IDLE_LOAD 1

#define POWERNODECONSTS_CAMERA_IDLE_LOAD 10

#define POWERNODECONSTS_DOORCONTROL_IDLE_LOAD 5

#define POWERNODECONSTS_VENDING_IDLE_LOAD 50

//############  depercated backwords compatiblity for use_power calls ######

#define POWERNODECONSTS_AIRLOCK_IDLE_LOAD 10
#define POWERNODECONSTS_AIRLOCK_ACTIVE_LOAD 10
#define POWERNODECONSTS_AIRLOCK_ACTIVE_TICKS 3


#define POWERNODECONSTS_TURBINE_IDLE_LOAD 10
#define POWERNODECONSTS_TURBINE_ACTIVE_LOAD 2800
#define POWERNODECONSTS_TURBINE_ACTIVE_TICKS 3


#define POWERNODECONSTS_TELEPORTER_IDLE_LOAD 10
#define POWERNODECONSTS_TELEPORTER_ACTIVE_LOAD 5000
#define POWERNODECONSTS_TELEPORTER_ACTIVE_TICKS 3


#define POWERNODECONSTS_GATEWAY_IDLE_LOAD 10
#define POWERNODECONSTS_GATEWAY_ACTIVE_LOAD 5000
#define POWERNODECONSTS_GATEWAY_ACTIVE_TICKS 3

#define POWERNODECONSTS_RDCONSOLE_IDLE_LOAD 10
#define POWERNODECONSTS_RDCONSOLE_ACTIVE_LOAD 2000
#define POWERNODECONSTS_RDCONSOLE_ACTIVE_TICKS 3


#define POWERNODECONSTS_AUTOLATHE_IDLE_LOAD 10
#define POWERNODECONSTS_AUTOLATHE_ACTIVE_LOAD 2000
#define POWERNODECONSTS_AUTOLATHE_ACTIVE_TICKS 3

#define POWERNODECONSTS_IGNITER_IDLE_LOAD 10
#define POWERNODECONSTS_IGNITER_ACTIVE_LOAD 1000
#define POWERNODECONSTS_IGNITER_ACTIVE_LOAD_HAND_USE 50
#define POWERNODECONSTS_IGNITER_ACTIVE_TICKS 3

#define POWERNODECONSTS_FLASHER_IDLE_LOAD 5
#define POWERNODECONSTS_FLASHER_ACTIVE_LOAD 1000
#define POWERNODECONSTS_FLASHER_ACTIVE_TICKS 1

#define POWERNODECONSTS_CELLCHARGER_IDLE_LOAD 10
#define POWERNODECONSTS_CELLCHARGER_ACTIVE_LOAD 200
#define POWERNODECONSTS_CELLCHARGER_ACTIVE_TICKS 1

#define POWERNODECONSTS_TELESCICOMPUTER_IDLE_LOAD 5
#define POWERNODECONSTS_TELESCICOMPUTER_ACTIVE_LOAD 50
#define POWERNODECONSTS_TELESCICOMPUTER_ACTIVE_TICKS 2

#define POWERNODECONSTS_CLONING_IDLE_LOAD 5
#define POWERNODECONSTS_CLONING_ACTIVE_LOAD 7500
#define POWERNODECONSTS_CLONING_ACTIVE_TICKS 2


#define POWERNODECONSTS_TURRETS_IDLE_LOAD 50
#define POWERNODECONSTS_TURRETS_ACTIVE_LOAD_SHOT 500
#define POWERNODECONSTS_TURRETS_ACTIVE_LOAD_STUN 300
#define POWERNODECONSTS_TURRETS_ACTIVE_TICKS 2

#define POWERNODECONSTS_PORTABLE_TURRET_IDLE_LOAD 50
#define POWERNODECONSTS_PORTABLE_TURRET_ACTIVE_LOAD 300
#define POWERNODECONSTS_PORTABLE_TURRET_ACTIVE_TICKS 2

#define POWERNODECONSTS_TRANSFORMER_IDLE_LOAD 50
#define POWERNODECONSTS_TRANSFORMER_ACTIVE_LOAD 5000
#define POWERNODECONSTS_TRANSFORMER_ACTIVE_TICKS 2

#define POWERNODECONSTS_BIOGENERATOR_IDLE_LOAD 40
#define POWERNODECONSTS_BIOGENERATOR_ACTIVE_LOAD_PERCONTENTS 30
#define POWERNODECONSTS_BIOGENERATOR_ACTIVE_TICKS 2
///powerUtils.use_power(powerNode,POWERNODECONSTS_PROCESSOR_ACTIVE_LOAD_PERCOMPONENT,POWERNODECONSTS_PROCESSOR_ACTIVE_TICKS)


#define POWERNODECONSTS_PROTOLATHE_IDLE_LOAD 40
#define POWERNODECONSTS_PROTOLATHE_ACTIVE_LOAD_MIN 1000
#define POWERNODECONSTS_PROTOLATHE_ACTIVE_TICKS 2

#define POWERNODECONSTS_PORTABLE_TURRET_IDLE_LOAD 50
#define POWERNODECONSTS_PORTABLE_TURRET_ACTIVE_LOAD 300
#define POWERNODECONSTS_PORTABLE_TURRET_ACTIVE_TICKS 2


#define POWERNODECONSTS_PROCESSOR_IDLE_LOAD 10
#define POWERNODECONSTS_PROCESSOR_ACTIVE_LOAD_PERCOMPONENT 500
#define POWERNODECONSTS_PROCESSOR_ACTIVE_TICKS 1






